In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("suraj520/customer-support-ticket-dataset")

print("Path to dataset files:", path)

/opt/anaconda3/envs/my_python_env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|████████████████████████████████████████| 828k/828k [00:00<00:00, 1.32MB/s]

Extracting files...
Path to dataset files: /Users/danieljanini/.cache/kagglehub/datasets/suraj520/customer-support-ticket-dataset/versions/1


In [8]:
import pandas as pd
import numpy as np 
datapath = path + '/customer_support_tickets.csv'
data = pd.read_csv(datapath)

In [24]:
data.head(10)

Ticket ID        Customer Name              Customer Email  Customer Age  \
0          1        Marisa Obrien  carrollallison@example.com            32   
1          2         Jessica Rios    clarkeashley@example.com            42   
2          3  Christopher Robbins   gonzalestracy@example.com            48   
3          4     Christina Dillon    bradleyolson@example.org            27   
4          5    Alexander Carroll     bradleymark@example.com            67   
5          6      Rebecca Fleming     sheenasmith@example.com            53   
6          7    Jacqueline Wright     donaldkeith@example.org            24   
7          8           Denise Lee    joelwilliams@example.com            23   
8          9       Nicolas Wilson        joshua24@example.com            60   
9         10       William Dawson          clopez@example.com            27   

  Customer Gender        Product Purchased Date of Purchase  \
0           Other               GoPro Hero       2021-03-22   
1          Female              LG Smart TV       2021-05-22   
2           Other                 Dell XPS       2020-07-14   
3          Female         Microsoft Office       2020-11-13   
4          Female         Autodesk AutoCAD       2020-02-04   
5            Male         Microsoft Office       2020-07-28   
6           Other        Microsoft Surface       2020-02-23   
7            Male       Philips Hue Lights       2020-08-09   
8           Other  Fitbit Versa Smartwatch       2020-07-16   
9            Male     Dyson Vacuum Cleaner       2020-03-06   

            Ticket Type            Ticket Subject  \
0       Technical issue             Product setup   
1       Technical issue  Peripheral compatibility   
2       Technical issue           Network problem   
3       Billing inquiry            Account access   
4       Billing inquiry                 Data loss   
5  Cancellation request             Payment issue   
6       Product inquiry            Refund request   
7        Refund request              Battery life   
8       Technical issue      Installation support   
9        Refund request             Payment issue   

                                  Ticket Description  \
0  I'm having an issue with the {product_purchase...   
1  I'm having an issue with the {product_purchase...   
2  I'm facing a problem with my {product_purchase...   
3  I'm having an issue with the {product_purchase...   
4  I'm having an issue with the {product_purchase...   
5  I'm facing a problem with my {product_purchase...   
6  I'm unable to access my {product_purchased} ac...   
7  I'm having an issue with the {product_purchase...   
8  I'm having an issue with the {product_purchase...   
9  My {product_purchased} is making strange noise...   

               Ticket Status                                     Resolution  \
0  Pending Customer Response                                            NaN   
1  Pending Customer Response                                            NaN   
2                     Closed   Case maybe show recently my computer follow.   
3                     Closed  Try capital clearly never color toward story.   
4                     Closed                    West decision evidence bit.   
5                       Open                                            NaN   
6                       Open                                            NaN   
7                       Open                                            NaN   
8  Pending Customer Response                                            NaN   
9  Pending Customer Response                                            NaN   

  Ticket Priority Ticket Channel  First Response Time   Time to Resolution  \
0        Critical   Social media  2023-06-01 12:15:36                  NaN   
1        Critical           Chat  2023-06-01 16:45:38                  NaN   
2             Low   Social media  2023-06-01 11:14:38  2023-06-01 18:05:38   
3             Low   Social media  2023-06-01 07:29:40  2

## Tokenization of the ticket descriptions

In [46]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = np.array(data["Ticket Description"])
tokenizer = Tokenizer(oov_token = "<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'the': 2, 'product': 3, 'purchased': 4, 'issue': 5, 'to': 6, "i'm": 7, 'my': 8, 'please': 9, 'with': 10, 'it': 11, 'an': 12, 'a': 13, 'having': 14, 'assist': 15, 'and': 16, "i've": 17, 'i': 18, 'is': 19, 'you': 20, 'but': 21, 'this': 22, 'on': 23, 'in': 24, 'for': 25, 'of': 26, 'be': 27, 'that': 28, 'problem': 29, 'not': 30, 'can': 31, 'if': 32, 'any': 33, 'or': 34, 'your': 35, 'there': 36, 'data': 37, 'as': 38, 'what': 39, 'have': 40, 'software': 41, 'me': 42, 'account': 43, 'steps': 44, 'other': 45, 'are': 46, 'error': 47, 'up': 48, "it's": 49, 'noticed': 50, 'how': 51, 'help': 52, 'persists': 53, 'resolve': 54, 'update': 55, 'message': 56, 'would': 57, 'device': 58, 'unable': 59, 'could': 60, 'tried': 61, 'using': 62, 'need': 63, 'support': 64, "'": 65, 'started': 66, 'use': 67, 'times': 68, 'do': 69, 'fine': 70, 'available': 71, 'facing': 72, 'made': 73, 'already': 74, 'will': 75, 'so': 76, "didn't": 77, 'from': 78, 'we': 79, '1': 80, 'might': 81, 'checked': 82, 'relat

## Creating sequences 

In [48]:
sequences = tokenizer.texts_to_sequences(sentences)

In [52]:
from tensorflow.keras import utils
padded = utils.pad_sequences(sequences)

In [54]:
print(padded)

[[  0   0   0 ...   2   5  53]
 [  0   0   0 ... 135  48 136]
 [  0   0   0 ...  30 231 158]
 ...
 [  0   0   0 ...  11  77  52]
 [  0   0   0 ...   8   3   4]
 [  0   0   0 ...  54   2  29]]
